#!/bin/bash
if [ -e "./kernel-6.1" ];then
./build.sh kernel && cd buildroot && rmake janus-gateway && rmake ustreamer && rmake kvmd-bin && rmake python-kvmd && (rmake glweb || true) && cd ..  &&  ./build.sh rootfs && ./build.sh updateimg
else
./build.sh kernel && rmake janus-gateway && rmake ustreamer && rmake kvmd-bin && rmake python-kvmd && (rmake glweb || true) &&  ./build.sh rootfs && ./build.sh updateimg
fi
